In [2]:
#1
import numpy as np

In [ ]:
#2
# Générer un tableau de 10 éléments
tableau1 = np.random.randint(0, 10, size=10)

# Générer un tableau de 5x5 éléments
tableau2 = np.random.randint(0, 10, size=(5, 5))

# Générer un tableau de 3x3x3 éléments
tableau3 = np.random.randint(0, 10, size=(3, 3, 3))

print("Tableau 1:\n", tableau1)
print("Tableau 2:\n", tableau2)
print("Tableau 3:\n", tableau3)

Tableau 1:
 [7 8 6 2 6 9 2 1 0 9]
Tableau 2:
 [[0 0 6 9 0]
 [0 1 3 7 5]
 [5 6 5 5 3]
 [9 9 7 3 4]
 [7 8 6 6 6]]
Tableau 3:
 [[[4 4 7]
  [7 8 5]
  [6 1 6]]

 [[1 3 5]
  [1 5 7]
  [7 4 6]]

 [[8 7 8]
  [2 3 2]
  [1 7 3]]]


In [ ]:
# Afficher le shape des tableaux
print("Shape du tableau 1:", tableau1.shape)
print("Shape du tableau 2:", tableau2.shape)
print("Shape du tableau 3:", tableau3.shape)


Shape du tableau 1: (10,)
Shape du tableau 2: (5, 5)
Shape du tableau 3: (3, 3, 3)


In [ ]:
#4
# Afficher la taille (size) des tableaux
print("Taille du tableau 1:", tableau1.size)
print("Taille du tableau 2:", tableau2.size)
print("Taille du tableau 3:", tableau3.size)


Taille du tableau 1: 10
Taille du tableau 2: 25
Taille du tableau 3: 27


In [ ]:
#5
# Afficher le nombre de dimensions (ndim) des tableaux
print("Nombre de dimensions du tableau 1:", tableau1.ndim)
print("Nombre de dimensions du tableau 2:", tableau2.ndim)
print("Nombre de dimensions du tableau 3:", tableau3.ndim)


Nombre de dimensions du tableau 1: 1
Nombre de dimensions du tableau 2: 2
Nombre de dimensions du tableau 3: 3


In [ ]:
#6
# Afficher le type de données (dtype) des tableaux
print("Type de données du tableau 1:", tableau1.dtype)
print("Type de données du tableau 2:", tableau2.dtype)
print("Type de données du tableau 3:", tableau3.dtype)


Type de données du tableau 1: int64
Type de données du tableau 2: int64
Type de données du tableau 3: int64


In [ ]:
#7
# Afficher les premiers et deuxièmes éléments du premier tableau
print("Premier élément du tableau 1:", tableau1[0])
print("Deuxième élément du tableau 1:", tableau1[1])


Premier élément du tableau 1: 7
Deuxième élément du tableau 1: 8


In [ ]:
# Afficher le dernier et l'avant-dernier élément du premier tableau
print("Dernier élément du tableau 1:", tableau1[-1])
print("Avant-dernier élément du tableau 1:", tableau1[-2])


Dernier élément du tableau 1: 9
Avant-dernier élément du tableau 1: 0


In [ ]:
# Afficher le contenu du tableau 2
print("Contenu du tableau 2:\n", tableau2)


Contenu du tableau 2:
 [[0 0 6 9 0]
 [0 1 3 7 5]
 [5 6 5 5 3]
 [9 9 7 3 4]
 [7 8 6 6 6]]


In [ ]:
# Afficher l'élément en première position du tableau 2
print("Premier élément du tableau 2:", tableau2[0, 0])

Premier élément du tableau 2: 0


In [ ]:
# Afficher l'élément sur la dernière ligne et avant-dernière colonne du tableau 2
print("Élément sur la dernière ligne et avant-dernière colonne du tableau 2:", tableau2[-1, -2])


Élément sur la dernière ligne et avant-dernière colonne du tableau 2: 6


In [ ]:
# Remplacer le premier élément du tableau 1 par 50
tableau1[0] = 50

# Afficher le tableau mis à jour
print("Tableau 1 après modification:", tableau1)


Tableau 1 après modification: [50  8  6  2  6  9  2  1  0  9]


In [ ]:
# Ajouter la valeur 3.15896 à la première position du tableau 1
tableau1[0] = 3.15896

# Afficher le tableau mis à jour
print("Tableau 1 après ajout de la valeur:", tableau1)


Tableau 1 après ajout de la valeur: [3 8 6 2 6 9 2 1 0 9]


In [ ]:
#Etape 2 : le Array Slicing sur un tableau numpy : les sous-tableaux

# Créer un tableau d'entiers avec arange
nouveau_tableau = np.arange(10)

# Afficher le nouveau tableau
print("Nouveau tableau d'entiers:", nouveau_tableau)


Nouveau tableau d'entiers: [0 1 2 3 4 5 6 7 8 9]


In [ ]:
# Extraire les cinq premiers éléments du tableau précédant
sous_tableau = nouveau_tableau[:5]

# Afficher le sous-tableau
print("Sous-tableau des cinq premiers éléments:", sous_tableau)


Sous-tableau des cinq premiers éléments: [0 1 2 3 4]


In [ ]:
# Extraire les cinq derniers éléments du tableau précédant
sous_tableau = nouveau_tableau[-5:]

# Afficher le sous-tableau
print("Sous-tableau des cinq derniers éléments:", sous_tableau)


Sous-tableau des cinq derniers éléments: [5 6 7 8 9]


In [ ]:
# Afficher les éléments d'indices pairs dans un tableau
elements_pairs = tableau1[::2]

# Afficher les éléments d'indices pairs
print("Éléments d'indices pairs dans le tableau 1:", elements_pairs)


Éléments d'indices pairs dans le tableau 1: [3 6 6 2 0]


In [ ]:
# Afficher les éléments d'indices pairs à partir du troisième élément dans un tableau
elements_pairs = tableau1[2::2]

# Afficher les éléments d'indices pairs à partir du troisième élément
print("Éléments d'indices pairs à partir du troisième élément dans le tableau 1:", elements_pairs)

Éléments d'indices pairs à partir du troisième élément dans le tableau 1: [6 6 2 0]


In [ ]:
# Inverser un tableau avec la notation de tranche
tableau_inverse = tableau1[::-1]

# Afficher le tableau inversé
print("Tableau 1 inversé:", tableau_inverse)

Tableau 1 inversé: [9 0 1 2 9 6 2 6 8 3]


In [ ]:
# Création d'une matrice 3x4 pour l'exemple
matrice = np.array([[1, 2, 3, 4],
                    [5, 6, 7, 8],
                    [9, 10, 11, 12]])

# Afficher la sous-matrice des deux premières lignes et trois premières colonnes
sous_matrice = matrice[:2, :3]

# Afficher la sous-matrice résultante
print("Sous-matrice des deux premières lignes et trois premières colonnes :\n", sous_matrice)

Sous-matrice des deux premières lignes et trois premières colonnes :
 [[1 2 3]
 [5 6 7]]


In [ ]:
# Prenons une matrice 4x4 comme exemple
matrice = np.array([[1, 2, 3, 4],
                    [5, 6, 7, 8],
                    [9, 10, 11, 12],
                    [13, 14, 15, 16]])

# Afficher toutes les lignes avec les deux premières colonnes à pas de deux
resultat = matrice[:,:2:2]

# Afficher le résultat
print("Résultat : ", resultat)

Résultat :  [[ 1]
 [ 5]
 [ 9]
 [13]]


In [7]:
# Prenons une matrice 4x4 comme exemple
matrice = np.array([[1, 2, 3, 4],
                    [5, 6, 7, 8],
                    [9, 10, 11, 12],
                    [13, 14, 15, 16]])

# Inverser l'ordre des éléments dans la matrice
matrice_inversee = matrice[::-1, ::-1]

# Afficher la matrice inversée
print("Matrice inversée :\n", matrice_inversee)


Matrice inversée :
 [[16 15 14 13]
 [12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


In [8]:
# Afficher la première colonne de la matrice
premiere_colonne = matrice[:, 0]

# Afficher le résultat
print("Première colonne de la matrice :\n", premiere_colonne)

Première colonne de la matrice :
 [ 1  5  9 13]


In [9]:
# Afficher la première ligne de la matrice
premiere_ligne = matrice[0, :]

# Afficher le résultat
print("Première ligne de la matrice :\n", premiere_ligne)

Première ligne de la matrice :
 [1 2 3 4]


In [10]:
# Obtenir une vue 2x2 de la matrice pour les deux premières lignes et colonnes
vue_2x2 = matrice[:2, :2]

# Afficher la vue 2x2
print("Vue 2x2 de la matrice :\n", vue_2x2)

Vue 2x2 de la matrice :
 [[1 2]
 [5 6]]


In [11]:
vue_2x2[0, 0] = 99

# Afficher la vue modifiée
print("Vue 2x2 modifiée :\n", vue_2x2)

#question 27
# Afficher la matrice originale pour voir l'impact de la modification
print("Matrice originale après modification :\n", matrice)

# question 28
#La modification apportée à la vue 2x2 a également modifié la matrice originale.
#En effet, lorsque vous créez une vue sur une matrice NumPy,
 #vous ne créez pas une copie indépendante des données.
 #Au lieu de cela, la vue partage les mêmes données sous-jacentes que la matrice originale.
#Toute modification apportée à la vue se répercute donc directement sur la matrice originale.


Vue 2x2 modifiée :
 [[99  2]
 [ 5  6]]
Matrice originale après modification :
 [[99  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [16]:
#29
# Créer une copie explicite de ce sous-tableau
copie_2x2 = vue_2x2.copy()
#30
# Modifier la copie pour montrer qu'elle est indépendante de la matrice originale
copie_2x2[0, 0] = 50005
# Afficher la matrice originale pour vérifier qu'elle n'a pas été modifiée
print("Matrice originale après modification de la copie :\n", matrice)

# Afficher la copie pour vérifier la modification
print("Copie 2x2 modifiée :\n", copie_2x2)

Matrice originale après modification de la copie :
 [[99  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Copie 2x2 modifiée :
 [[50005     2]
 [    5     6]]


In [17]:
# Créer un tableau composé par des nombres allant de 1 à 9
tableau32 = np.arange(1, 10)

# Répartir les nombres sur 3 lignes et 3 colonnes en utilisant reshape
tableau_reshaped = tableau32.reshape(3, 3)

# Afficher le tableau reshaped
print("Tableau 3x3 reshaped :\n", tableau_reshaped)

Tableau 3x3 reshaped :
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [22]:
#question 33
# Créer un vecteur unidimensionnel
vecteur = np.array([1, 2, 3])

# Reshaper en un vecteur à deux dimensions (1 ligne, 3 colonnes)
vecteur_reshaped_1x3 = vecteur.reshape(1, 3)

# Afficher le vecteur reshaped
print("Vecteur reshaped (1x3) :\n", vecteur_reshaped_1x3)

#question 34
# Reshaper en un vecteur à deux dimensions (3 lignes, 1 colonne)
vecteur_colonne= vecteur.reshape(3, 1)

# Afficher le vecteur reshaped
print("Vecteur colonne :\n", vecteur_colonne)


Vecteur reshaped (1x3) :
 [[1 2 3]]
Vecteur colonne :
 [[1]
 [2]
 [3]]


In [24]:
# Créer deux tableaux
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

#### Concaténer les deux tableaux en un seul tableau
concatenated_array = np.concatenate((array1, array2))

# Afficher le tableau concaténé
print("Tableau concaténé :\n", concatenated_array)

####Concaténer les deux tableaux verticalement
vertical_stack = np.vstack((array1, array2))

# Afficher le résultat de la concaténation verticale
print("Concaténation verticale :\n", vertical_stack)

#### Reshape les tableaux pour qu'ils aient une dimension supplémentaire
array1_reshaped = array1.reshape(-1, 1)
array2_reshaped = array2.reshape(-1, 1)

# Concaténer les deux tableaux horizontalement
horizontal_stack = np.hstack((array1_reshaped, array2_reshaped))

# Afficher le résultat de la concaténation horizontale
print("Concaténation horizontale :\n", horizontal_stack)



Tableau concaténé :
 [1 2 3 4 5 6]
Concaténation verticale :
 [[1 2 3]
 [4 5 6]]
Concaténation horizontale :
 [[1 4]
 [2 5]
 [3 6]]


In [31]:
#36


####Créer deux tableaux bidimensionnels
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])

# Concaténer les deux tableaux bidimensionnels le long de la première dimension
concatenated_array_axis0 = np.concatenate((array1, array2), axis=0)

# Concaténer les deux tableaux bidimensionnels le long de la deuxième dimension
concatenated_array_axis1 = np.concatenate((array1, array2), axis=1)

# Afficher les résultats
print("Concaténation le long de la première dimension (axis=0) :\n", concatenated_array_axis0)
print("\nConcaténation le long de la deuxième dimension (axis=1) :\n", concatenated_array_axis1)

Concaténation le long de la première dimension (axis=0) :
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Concaténation le long de la deuxième dimension (axis=1) :
 [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [28]:
#37
# Créer deux tableaux bidimensionnels
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])
#Methode1
# Concaténer les deux tableaux bidimensionnels selon les colonnes
concatenated_columns = np.concatenate((array1, array2), axis=1)

# Afficher le résultat
print("Concaténation selon les colonnes (axis=1) :\n", concatenated_columns)

#Methode2
# Concaténer les deux tableaux bidimensionnels horizontalement (selon les colonnes)
horizontal_stack = np.hstack((array1, array2))

# Afficher le résultat
print("Concaténation horizontale (selon les colonnes) :\n", horizontal_stack)



Concaténation selon les colonnes (axis=1) :
 [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
Concaténation horizontale (selon les colonnes) :
 [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [29]:
#38
####Concaténer les deux tableaux bidimensionnels verticalement
vertical_stack = np.vstack((array1, array2))

# Afficher le résultat de la concaténation verticale
print("\nConcaténation verticale :\n", vertical_stack)


Concaténation verticale :
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [30]:
#39
##### Concaténer les deux tableaux bidimensionnels horizontalement
horizontal_stack = np.hstack((array1, array2))

# Afficher le résultat de la concaténation horizontale
print("\nConcaténation horizontale :\n", horizontal_stack)


Concaténation horizontale :
 [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
